version: "3"
services:
    bp_app:
        network_mode: host
        build:
            context: .
            dockerfile: "Dockerfile"
        volumes:
            - ..:/BP_app
        ports:
            - "8000:8000"
        command: /bin/sh -c "cd ./BP_app/bp_app && pip3 install -e . && while sleep 1000; do :; done"    