version: "3"
services:
    bp_app:
        network_mode: host
        build:
            context: .
            dockerfile: "Dockerfile"
        volumes:
            - ..:/BP_app
        ports:
            - "8000:8000"
        command: /bin/sh -c "cd ./BP_app && python3 -m venv env && . ./env/bin/activate && cd ./bp_app && pip3 install -r requirements.txt && python3 app.py"    