openapi: "3.0.0"
info:
  version: "0.1.0"
  title: BP API

servers:
  - url: http://localhost:6543
    description: Pyramid BP app

paths:
  /:
    get:
      responses:
        200:
          description: Say hello
          content:
            text/html: {}
        400:
          description: Bad Request

  /records:
    get:
      summary: Retrieve all records
      responses:
        200:
          description: All records returned
          content:
            text/html: {}
        400:
          description: Bad Request

  /records/{uid}:
    get:
      parameters:
        - name: uid
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      summary: Retrieve record based on uid
      responses:
        200:
          description: Record returned
          content:
            text/html: {}
        400:
          description: Bad Request
    delete:
      parameters:
        - name: uid
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      summary: Delete record based on uid
      responses:
        200:
          description: Record deleted
          content:
            text/html: {}
        400:
          description: Bad Request
    put:
      parameters:
        - name: uid
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      summary: Update record based on uid
      responses:
        200:
          description: Record updated
          content:
            text/html: {}
        400:
          description: Bad Request

