openapi: "3.0.0"
info:
  version: "0.1.0"
  title: BP API

servers:
  - url: http://localhost:6543
    description: Pyramid BP app

paths:
  /:
    get:
      responses:
        200:
          description: Say hello
          content:
            text/html: {}
        400:
          description: Bad Request

  /records:
    get:
      summary: Retrieve all records
      responses:
        200:
          description: All records returned
          content:
            text/html: {}
        400:
          description: Bad Request

  /records/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      summary: Retrieve record based on id
      responses:
        200:
          description: Record returned
          content:
            text/html: {}
        400:
          description: Bad Request
    delete:
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      summary: Delete record based on id
      responses:
        200:
          description: Record deleted
          content:
            text/html: {}
        400:
          description: Bad Request
    put:
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      summary: Update record based on id
      responses:
        200:
          description: Record updated
          content:
            text/html: {}
        400:
          description: Bad Request

components:

  schemas:

    Record:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 0
          example: 2
        bp_upper:
          type: integer
          format: int32
          minimum: 70
          maximum: 300
          example: 120
        bp_lower:
          type: integer
          format: int32
          minimum: 20
          maximum: 150
          example: 60
        timestamp:
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z"
        notes:
          type: string
          minLength: 1
          maxLength: 100
          example: Had a espresso one hour prior

