openapi: "3.0.0"
info:
  version: "0.1.0"
  title: BP API

servers:
  - url: http://localhost:6543
    description: Pyramid BP app

paths:
  /:
    get:
      responses:
        200:
          description: Say hello
          content:
            text/html: {}
        400:
          description: Bad Request

